spring:
  application:
    name: backend_eventRegistration

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    url: jdbc:postgresql://localhost:5432/event_registration
    username: postgres
    password: Zaw@2003postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
